# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fastflix' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher'
  pod 'Alamofire', '~> 5.0.0-beta.5'

  # Pods for Fastflix

end
